---
default: true

MD013:
  line_length: 120
  heading_line_length: 120
  headings: true # Enforce line length in headings, as they can affect readability
  strict: true # Do not ignore long lines in headings, as they can affect readability
  tables: false # Allow long lines in tables for readability
  code_blocks: false # Allow long lines in code blocks for readability

# https://updownpress.github.io/markdown-lint
MD024: false # Allow duplicate headings
MD025: false # Allow multiple top-level headings
MD036: false # Allow emphasis used instead of a header
MD041: false # Allow first line to be a top-level heading
